export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const USER_POSTS_STATE_CHANGE = "USER_POSTS_STATE_CHANGE";
export const FOLLOWING_STATE_CHANGE = "FOLLOWING_STATE_CHANGE";
export const USERS_DATA_STATE_CHANGE = "USERS_DATA_STATE_CHANGE";
export const USERS_POSTS_STATE_CHANGE = "USERS_POSTS_STATE_CHANGE";
export const CLEAR_DATA = "CLEAR_DATA";
